server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestao_estagio_db
    username: ${MYSQL_USER}
    password: ${MYSQL_SECRET}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:domain-tables-db.sql
    data: classpath:data-db.sql
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: thamires.agnes12@gmail.com
    password: ${GESTAO_ESTAGIO_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: ${PROFILE}
bucket: ${DOCUMENT_STORING_FOLDER}