server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestao-estagio-db
    username: root
    password: stratus1011
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:domain-tables-db.sql
    data: classpath:data-db.sql
  jpa:
    hibernate:
      ddl-auto: create
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
